# Generated by Django 2.0.7 on 2023-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pnumber', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('reIdentity', models.CharField(max_length=200)),
                ('Identity', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'register',
            },
        ),
    ]
